version: '3'

services:
  app:
    container_name: nextjs
    platform: linux/amd64
    build:
      context: .
    ports:
      - '443:443'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
